
include: package:strict/analysis_options.yaml
analyzer:
 
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    argument_type_not_assignable: false
    implicit_dynamic_map_literal: false
    implicit-dynamic: false
    avoid_dynamic_calls: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    unnecessary_getters_setters: false
